#!/usr/bin/env bash
# Mimi's configuration file for ubuntu ssh server.

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    PubkeyAuthentication yes
    RSAAuthentication yes
    AuthorizedKeysFile .ssh/authorized_keys
