#!/usr/bin/env bash
# SSH client configuration file

Host *
      	PasswordAuthentication no
      	IdentifyFile ~/.ssh/school
	SendEnv LANG LC_*
	HashKnownHosts yes
	GSSAPIAuthentication yes
	GSSAPIDelegateCredentials no
	
